# Generated by Django 4.2.4 on 2023-09-28 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('video_url', models.URLField()),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserForProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userown', to='business.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productspos', to='business.userforproduct')),
            ],
        ),
        migrations.CreateModel(
            name='UserLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_time', models.IntegerField()),
                ('status', models.TextField(choices=[('Viewed', 'Просмотрено'), ('Not viewed', 'Не просмотрено')], default='Not viewed')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='business.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='business.userforproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prods', to='business.lesson')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='business.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ManyToManyField(through='business.UserProduct', to='business.userforproduct'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='product',
            field=models.ManyToManyField(through='business.ProductLesson', to='business.product'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='viewed',
            field=models.ManyToManyField(through='business.UserLesson', to='business.userforproduct'),
        ),
    ]
